name: Firebase Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Build
        env:
          CI: false
        run: npm run build

      - name: Debug Build Directory
        run: ls -la dist  # Cambiado de "build" a "dist"

      - name: Archive Production Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist  # Cambiado de "build" a "dist"

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist  # Asegura que esté disponible en el lugar esperado

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@v14.3.1  # Mejor usar versión estable
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
